from datetime import UTC, datetime

from app.constants import ProjectCategory, ProjectPriority, ProjectStatus

SEED_PROJECTS = [
    {
        "id": "VELODESK-24",
        "title": "VD-24 Logout redirect lands on blank screen",
        "description": "After signing out, users see a blank page instead of returning to the VeloDesk sign-in screen.",
        "category": ProjectCategory.BUG.value,
        "status": ProjectStatus.IN_PROGRESS.value,
        "priority": ProjectPriority.HIGH.value,
        "progress": 45,
        "tags": ["auth", "frontend"],
        "resource_url": "",
        "notes": "Reproducible in Chrome and Edge.",
        "created_at": datetime(2026, 7, 1, 9, 0, tzinfo=UTC),
        "updated_at": datetime(2026, 7, 10, 14, 30, tzinfo=UTC),
    },
    {
        "id": "VELODESK-31",
        "title": "VD-31 Saved filter presets for workspaces",
        "description": "As a team lead, I want reusable filter presets so members can quickly surface the work items they care about.",
        "category": ProjectCategory.STORY.value,
        "status": ProjectStatus.NOT_STARTED.value,
        "priority": ProjectPriority.HIGH.value,
        "progress": 0,
        "tags": ["filters", "ux"],
        "resource_url": "",
        "notes": "",
        "created_at": datetime(2026, 7, 3, 11, 0, tzinfo=UTC),
        "updated_at": datetime(2026, 7, 3, 11, 0, tzinfo=UTC),
    },
    {
        "id": "VELODESK-38",
        "title": "VD-38 Normalize API validation responses",
        "description": "Return consistent field-level validation messages when creating or updating work items.",
        "category": ProjectCategory.TASK.value,
        "status": ProjectStatus.IN_PROGRESS.value,
        "priority": ProjectPriority.MEDIUM.value,
        "progress": 20,
        "tags": ["api", "backend"],
        "resource_url": "",
        "notes": "Match frontend form labels.",
        "created_at": datetime(2026, 7, 5, 8, 0, tzinfo=UTC),
        "updated_at": datetime(2026, 7, 12, 16, 0, tzinfo=UTC),
    },
    {
        "id": "VELODESK-12",
        "title": "VD-12 Q3 reliability program",
        "description": "Program-level tracking for uptime goals, incident follow-ups, and observability improvements.",
        "category": ProjectCategory.EPIC.value,
        "status": ProjectStatus.COMPLETED.value,
        "priority": ProjectPriority.MEDIUM.value,
        "progress": 100,
        "tags": ["epic", "ops"],
        "resource_url": "",
        "notes": "Closed after quarterly review.",
        "created_at": datetime(2026, 6, 20, 10, 0, tzinfo=UTC),
        "updated_at": datetime(2026, 7, 8, 9, 0, tzinfo=UTC),
    },
    {
        "id": "VELODESK-45",
        "title": "VD-45 Faster workspace list rendering",
        "description": "Improve first paint time when loading workspaces with large numbers of work items.",
        "category": ProjectCategory.IMPROVEMENT.value,
        "status": ProjectStatus.IN_PROGRESS.value,
        "priority": ProjectPriority.LOW.value,
        "progress": 60,
        "tags": ["performance", "ui"],
        "resource_url": "",
        "notes": "Target under 2s for 200 items.",
        "created_at": datetime(2026, 7, 14, 13, 0, tzinfo=UTC),
        "updated_at": datetime(2026, 7, 16, 10, 0, tzinfo=UTC),
    },
]
